baseURL = 'https://orl-gombert.ch/'
languageCode = 'en-fr'
title = 'Dre. MD Edwige Gombert - ORL Morges'
theme = 'agnes'
[params]
	authorName = "Jonathan Dan"

[params.content]
	LeadTitle = "ORL Morges"
	LeadDescription = "Bienvenue au cabinet de la Dre. M.D. Edwige Gombert médecin spécialiste FMH en Oto-Rhino-Laryngologie."
	ButtonCaption = "Prendre rendez-vous"
	ButtonURL = "#rdv"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Adresse"
	FeatureDescription = "<a href='https://maps.app.goo.gl/jFXLACx2ugGXcYUEA' target='_blank'>Chemin des Terrasses 1 <br> 1110 Morges</a>"
	FeatureImage = "images/feature-1.png"
	FeatureLink = "#adresse"
	
[[params.feature]]
	FeatureTitle = "Rendez-vous"
	FeatureDescription = "<ul><li>Lundi: 13h30 - 16h30</li><li>Mardi & Mercredi: 8h-12h & 13h30-16h30</li><li>Jeudi: 8h00 - 18h00</li></ul><a href='tel:+41218014971'>021 801 49 71</a>"
	FeatureImage = "images/feature-2.png"
	FeatureLink = "#rdv"

[[params.feature]]
	FeatureTitle = "Expertises"
    FeatureEnvironment = "ul"
	FeatureDescription = "<li>Nez, gorge, oreilles</li><li>Ultrason cervical</li><li>Audiométrie</li>"
	FeatureImage = "images/feature-3.png"
	FeatureLink = "#expertise"
	
[[params.feature]]
	FeatureTitle = "À propos"
	FeatureDescription = "Dre. M.D. Edwige Gombert médecin spécialiste <br> FMH en <br> Oto-Rhino-Laryngologie"
	FeatureImage = "images/feature-4.png"
	FeatureLink = "#about"
	
